name = "Luminal"
authors = ["Gemini"]
version = "0.1.0"

[deps]
Metatheory = "e9d8d322-4543-424a-9be4-0cc815abe26c"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
julia = "1.9"
